### PR TITLE
[ready] integrate map completeness stats

### PR DESCRIPTION
**Pull request by geohacker**
* [x] creates a tileset
* [ ] use the tileset for stats per aoi.

cc @kamicut

### CODE REVIEW

**Comment by kamicut** [comment]
@geohacker are the names going to be exact for $COUNTRY? Maybe we should use iso3 so there's no manual guessing?

**Comment by geohacker** [comment]
@kamicut yeah I agree. So far we've just been using the full country name because that's what QA tiles uses.

**Comment by kamicut** [comment]
@geohacker is there a mapping between the QA tile names and country names we could use?

**Review by kamicut — COMMENTED** [review]
Why is the initial wget commented out?

**Comment by kamicut** [comment]
I tried to replicate this but map-completeness-tiles.js was not pushed? @geohacker

**Comment by kamicut** [comment]
We can merge this in.

**Comment by geohacker** [comment]
Sounds good! I'll make the aoi aggregates to another PR.

**Pull request merged**
